productDetabase =[
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:60,
        aprice:250,
        cat:"covid",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:20,
        aprice:500,
        cat:"diabetes",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"eyewear",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:20,
        aprice:500,
        cat:"ayush",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"fitness",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:20,
        aprice:500,
        cat:"mom",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:20,
        aprice:500,
        cat:"diveces",
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:500,
        cat:"surgicals",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"sexual",
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:20,
        aprice:500,
        cat:"treatments",
    },
]
localStorage.setItem("productDetaBase",JSON.stringify(productDetabase))