productDetabase =[
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:30,
        aprice:300,
        cat:"covid",
        rat:4.5,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:10,
        aprice:450,
        cat:"diabetes",
        rat:4,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:15,
        aprice:670,
        cat:"eyewear",
        rat:5,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:25,
        aprice:290,
        cat:"ayush",
        rat:3
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:12,
        aprice:880,
        cat:"fitness",
        rat:4.1,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:30,
        aprice:890,
        cat:"mom",
        rat:4.2,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:22,
        aprice:560,
        cat:"diveces",
        rat:4.3,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:28,
        aprice:580,
        cat:"surgicals",
        rat:4.2,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:30,
        aprice:780,
        cat:"sexual",
        rat:4.2,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:30,
        aprice:670,
        cat:"treatments",
        rat:3.1,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:25,
        aprice:780,
        cat:"covid",
        rat:3.4,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:23,
        aprice:678,
        cat:"diabetes",
        rat:2.1,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:32,
        aprice:767,
        cat:"eyewear",
        rat:4.1,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:33,
        aprice:675,
        cat:"ayush",
        rat:4.1,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:35,
        aprice:654,
        cat:"fitness",
        rat:5,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:22,
        aprice:655,
        cat:"mom",
        rat:4.5,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:27,
        aprice:675,
        cat:"diveces",
        rat:3.4,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:32,
        aprice:564,
        cat:"surgicals",
        rat:4.6,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:34,
        aprice:545,
        cat:"sexual",
        rat:4.7,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:35,
        aprice:564,
        cat:"treatments",
        rat:4.3,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:28,
        aprice:250,
        cat:"covid",
        rat:4.1,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:36,
        aprice:546,
        cat:"diabetes",
        rat:3.6,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:26,
        aprice:767,
        cat:"eyewear",
        rat:5.7,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:28,
        aprice:754,
        cat:"ayush",
        rat:5.3,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:32,
        aprice:453,
        cat:"fitness",
        rat:5.8,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:36,
        aprice:654,
        cat:"mom",
        rat:4.65456,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:40,
        aprice:560,
        cat:"diveces",
        rat:4.454,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:20,
        aprice:675,
        cat:"surgicals",
        rat:4.4523,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:26,
        aprice:565,
        cat:"sexual",
        rat:4.6345,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:32,
        aprice:765,
        cat:"treatments",
        rat:4.66456,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:38,
        aprice:243,
        cat:"covid",
        rat:4.746,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:37,
        aprice:756,
        cat:"diabetes",
        rat:4.5645744,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:29,
        aprice:454,
        cat:"eyewear",
        rat:4.6765,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:35,
        aprice:655,
        cat:"ayush",
        rat:4.5654,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:34,
        aprice:676,
        cat:"fitness",
        rat:4.3545,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:25,
        aprice:235,
        cat:"mom",
        rat:4.3565,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:36,
        aprice:768,
        cat:"diveces",
        rat:4.6436,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:32,
        aprice:567,
        cat:"surgicals",
        rat:4.65474,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:28,
        aprice:623,
        cat:"sexual",
        rat:4.43524,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:32,
        aprice:135,
        cat:"treatments",
        rat:4.346,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:35,
        aprice:678,
        cat:"covid",
        rat:4.534,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:34,
        aprice:567,
        cat:"diabetes",
        rat:4.7756,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:27,
        aprice:787,
        cat:"eyewear",
        rat:4.6557,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:42,
        aprice:677,
        cat:"ayush",
        rat:4.567,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:37,
        aprice:633,
        cat:"fitness",
        rat:4.354,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:26,
        aprice:767,
        cat:"mom",
        rat:4.2453,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:31,
        aprice:213,
        cat:"diveces",
        rat:4.4564,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:42,
        aprice:543,
        cat:"surgicals",
        rat:4.325,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:32,
        aprice:232,
        cat:"sexual",
        rat:4.24213,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:36,
        aprice:757,
        cat:"treatments",
        rat:4.424,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:35,
        aprice:687,
        cat:"covid",
        rat:4.353425,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:36,
        aprice:9764,
        cat:"diabetes",
        rat:4.452,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:27,
        aprice:445,
        cat:"eyewear",
        rat:4.5423,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:42,
        aprice:656,
        cat:"ayush",
        rat:4.2454,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:37,
        aprice:867,
        cat:"fitness",
        rat:4.2344,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:41,
        aprice:566,
        cat:"mom",
        rat:4.6753,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:43,
        aprice:877,
        cat:"diveces",
        rat:4.6756,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:13,
        aprice:788,
        cat:"surgicals",
        rat:4.4634,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:15,
        aprice:678,
        cat:"sexual",
        rat:4.654,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:16,
        aprice:254,
        cat:"treatments",
        rat:4.345,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:18,
        aprice:786,
        cat:"covid",
        rat:4.6756,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:21,
        aprice:879,
        cat:"diabetes",
        rat:4.3453,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:22,
        aprice:532,
        cat:"eyewear",
        rat:4.5656,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:24,
        aprice:672,
        cat:"ayush",
        rat:4.3452,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:31,
        aprice:686,
        cat:"fitness",
        rat:4.243,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:25,
        aprice:435,
        cat:"mom",
        rat:4.2425,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:41,
        aprice:789,
        cat:"diveces",
        rat:4.2434,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:34,
        aprice:451,
        cat:"surgicals",
        rat:4.35432,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:41,
        aprice:787,
        cat:"sexual",
        rat:4.5423,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:31,
        aprice:874,
        cat:"treatments",
        rat:4.4324,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:15,
        aprice:867,
        cat:"covid",
        rat:4.34523,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:42,
        aprice:897,
        cat:"diabetes",
        rat:4.43523,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:16,
        aprice:877,
        cat:"eyewear",
        rat:4.867,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:41,
        aprice:244,
        cat:"ayush",
        rat:4.123,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:23,
        aprice:868,
        cat:"fitness",
        rat:4.2535,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:32,
        aprice:543,
        cat:"mom",
        rat:4.3243,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:34,
        aprice:898,
        cat:"diveces",
        rat:4.576,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:31,
        aprice:243,
        cat:"surgicals",
        rat:4.3241,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:32,
        aprice:873,
        cat:"sexual",
        rat:4.2314,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:21,
        aprice:243,
        cat:"treatments",
        rat:4.57656,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:23,
        aprice:674,
        cat:"covid",
        rat:4.4234,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:31,
        aprice:247,
        cat:"diabetes",
        rat:4.5465,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:34,
        aprice:889,
        cat:"eyewear",
        rat:4.2323,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:23,
        aprice:260,
        cat:"ayush",
        rat:4.6757,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:31,
        aprice:876,
        cat:"fitness",
        rat:4.4123,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:41,
        aprice:345,
        cat:"mom",
        rat:4.453,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:34,
        aprice:1456,
        cat:"diveces",
        rat:4.6546,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:31,
        aprice:2341,
        cat:"surgicals",
        rat:4.432,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:42,
        aprice:2345,
        cat:"sexual",
        rat:4.5325,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:31,
        aprice:881,
        cat:"treatments",
        rat:4.453,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:32,
        aprice:896,
        cat:"covid",
        rat:4.757,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:34,
        aprice:956,
        cat:"diabetes",
        rat:4.242345,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:32,
        aprice:248,
        cat:"eyewear",
        rat:4.5635,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:33,
        aprice:992,
        cat:"ayush",
        rat:4.6754,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:34,
        aprice:976,
        cat:"fitness",
        rat:4.4232,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:24,
        aprice:423,
        cat:"mom",
        rat:4.2445,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:32,
        aprice:678,
        cat:"diveces",
        rat:4.3412,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:23,
        aprice:2436,
        cat:"surgicals",
        rat:4.34132,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:32,
        aprice:2434,
        cat:"sexual",
        rat:4.2431,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:31,
        aprice:896,
        cat:"treatments",
        rat:4.2342,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:32,
        aprice:244,
        cat:"covid",
        rat:4.3425,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:31,
        aprice:768,
        cat:"diabetes",
        rat:4.575765,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:32,
        aprice:782,
        cat:"eyewear",
        rat:4.7867,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:13,
        aprice:2346,
        cat:"ayush",
        rat:4.757,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:32,
        aprice:245,
        cat:"fitness",
        rat:4.213,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:23,
        aprice:965,
        cat:"mom",
        rat:4.67665,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:32,
        aprice:1324,
        cat:"diveces",
        rat:4.3423,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:32,
        aprice:340,
        cat:"surgicals",
        rat:4.2434,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:23,
        aprice:267,
        cat:"sexual",
        rat:4.5645,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:34,
        aprice:752,
        cat:"treatments",
        rat:4.23432,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:21,
        aprice:257,
        cat:"covid",
        rat:4.756,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:23,
        aprice:238,
        cat:"diabetes",
        rat:4.675,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:24,
        aprice:567,
        cat:"eyewear",
        rat:4.234,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:12,
        aprice:895,
        cat:"ayush",
        rat:4.6456,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:32,
        aprice:249,
        cat:"fitness",
        rat:4.243,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:13,
        aprice:228,
        cat:"mom",
        rat:4.756,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:31,
        aprice:348,
        cat:"diveces",
        rat:4.4645,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:23,
        aprice:752,
        cat:"surgicals",
        rat:4.6575,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:32,
        aprice:139,
        cat:"sexual",
        rat:4.4345,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:13,
        aprice:234,
        cat:"treatments",
        rat:4.2344,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:32,
        aprice:2423,
        cat:"covid",
        rat:4.564,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:12,
        aprice:123,
        cat:"diabetes",
        rat:4.4565,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:21,
        aprice:853,
        cat:"eyewear",
        rat:4.564,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:43,
        aprice:424,
        cat:"ayush",
        rat:4.233,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:23,
        aprice:422,
        cat:"fitness",
        rat:4.7656,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:23,
        aprice:426,
        cat:"mom",
        rat:4.443,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:32,
        aprice:506,
        cat:"diveces",
        rat:4.5675,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:31,
        aprice:504,
        cat:"surgicals",
        rat:4.345,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:32,
        aprice:785,
        cat:"sexual",
        rat:4.4643,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:31,
        aprice:957,
        cat:"treatments",
        rat:4.456,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:12,
        aprice:238,
        cat:"covid",
        rat:4.5464,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:33,
        aprice:567,
        cat:"diabetes",
        rat:4.423,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:12,
        aprice:786,
        cat:"eyewear",
        rat:4.576,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:22,
        aprice:246,
        cat:"ayush",
        rat:4.234,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:32,
        aprice:746,
        cat:"fitness",
        rat:4.756,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:11,
        aprice:323,
        cat:"mom",
        rat:4.5645,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:32,
        aprice:862,
        cat:"diveces",
        rat:4.575,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:32,
        aprice:237,
        cat:"surgicals",
        rat:4.5675,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:12,
        aprice:792,
        cat:"sexual",
        rat:4.345,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:33,
        aprice:3453,
        cat:"treatments",
        rat:4.4645,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:32,
        aprice:237,
        cat:"covid",
        rat:4.534,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:43,
        aprice:335,
        cat:"diabetes",
        rat:4.456,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:32,
        aprice:854,
        cat:"eyewear",
        rat:4.564,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:34,
        aprice:2325,
        cat:"ayush",
        rat:4.456,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:23,
        aprice:3243,
        cat:"fitness",
        rat:4.2343,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:34,
        aprice:3427,
        cat:"mom",
        rat:4.5343,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:23,
        aprice:2345,
        cat:"diveces",
        rat:4.3434,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:34,
        aprice:345,
        cat:"surgicals",
        rat:4.345,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:43,
        aprice:2346,
        cat:"sexual",
        rat:4.23423,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:34,
        aprice:256,
        cat:"treatments",
        rat:4.23424,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:24,
        aprice:5356,
        cat:"covid",
        rat:4.4223,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:34,
        aprice:674,
        cat:"diabetes",
        rat:4.324,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:44,
        aprice:5060,
        cat:"eyewear",
        rat:4.533,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:23,
        aprice:346,
        cat:"ayush",
        rat:4.464,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:43,
        aprice:236,
        cat:"fitness",
        rat:4.5675,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:33,
        aprice:756,
        cat:"mom",
        rat:4.645,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:32,
        aprice:458,
        cat:"diveces",
        rat:4.645,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:43,
        aprice:785,
        cat:"surgicals",
        rat:4.456,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:23,
        aprice:674,
        cat:"sexual",
        rat:4.4554,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:34,
        aprice:789,
        cat:"treatments",
        rat:4.234,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:23,
        aprice:250,
        cat:"covid",
        rat:4.645,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:43,
        aprice:896,
        cat:"diabetes",
        rat:4.3245,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:33,
        aprice:896,
        cat:"eyewear",
        rat:4.456,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:23,
        aprice:673,
        cat:"ayush",
        rat:4.321,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:34,
        aprice:463,
        cat:"fitness",
        rat:4.643,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:43,
        aprice:675,
        cat:"mom",
        rat:4.564,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:23,
        aprice:7876,
        cat:"diveces",
        rat:4.234,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:34,
        aprice:234,
        cat:"surgicals",
        rat:4.564,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:32,
        aprice:678,
        cat:"sexual",
        rat:4.745,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:43,
        aprice:678,
        cat:"treatments",
        rat:4.423,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:32,
        aprice:685,
        cat:"covid",
        rat:4.563,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:32,
        aprice:867,
        cat:"diabetes",
        rat:4.65436,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:21,
        aprice:234,
        cat:"eyewear",
        rat:4.745,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:33,
        aprice:784,
        cat:"ayush",
        rat:4.643,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:24,
        aprice:2335,
        cat:"fitness",
        rat:4.564,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:31,
        aprice:784,
        cat:"mom",
        rat:4.564,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:32,
        aprice:234,
        cat:"diveces",
        rat:4.213,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:33,
        aprice:505,
        cat:"surgicals",
        rat:4.64,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:23,
        aprice:562,
        cat:"sexual",
        rat:4.234,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:23,
        aprice:674,
        cat:"treatments",
        rat:4.32,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:21,
        aprice:754,
        cat:"covid",
        rat:4.5234,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:32,
        aprice:234,
        cat:"diabetes",
        rat:4.654,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:34,
        aprice:896,
        cat:"eyewear",
        rat:4.54,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:34,
        aprice:235,
        cat:"ayush",
        rat:4.5743,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:23,
        aprice:876,
        cat:"fitness",
        rat:4.43,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:33,
        aprice:234,
        cat:"mom",
        rat:4.454,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:23,
        aprice:653,
        cat:"diveces",
        rat:4.657,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:21,
        aprice:867,
        cat:"surgicals",
        rat:4.63,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:42,
        aprice:3435,
        cat:"sexual",
        rat:4.634,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:42,
        aprice:234,
        cat:"treatments",
        rat:4.2545,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:22,
        aprice:250,
        cat:"covid",
        rat:4.2342,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:22,
        aprice:756,
        cat:"diabetes",
        rat:4.5532,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:54,
        aprice:1313,
        cat:"eyewear",
        rat:4.6754,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:32,
        aprice:124,
        cat:"ayush",
        rat:4.765,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:43,
        aprice:520,
        cat:"fitness",
        rat:4.564,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:43,
        aprice:563,
        cat:"mom",
        rat:4.654,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:22,
        aprice:744,
        cat:"diveces",
        rat:4.564,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:43,
        aprice:434,
        cat:"surgicals",
        rat:5.56,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:34,
        aprice:456,
        cat:"sexual",
        rat:4.354,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:34,
        aprice:564,
        cat:"treatments",
        rat:5.6,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/…z_e_alcohol_hand_rub_with_flip_cap_500_ml_0_1.jpg",
        name:"Shake HandZ-E Alcohol Hand Rub With Flip Cap 500 ml",
        mkt:"Inventz Lifesciences Pvt Ltd",
        dis:32,
        aprice:657,
        cat:"covid",
        rat:5.34,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/357753/d_protin_chocolate_powder_500_gm_0.jpg",
        name:"D Protin Chocolate Powder 500 gm",
        mkt:"British Biologicals",
        dis:34,
        aprice:675,
        cat:"diabetes",
        rat:5.34,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/909871/full_rim_incl_lenses_rectangle_grey_grey_medium_0_0.jpg",
        name:"InStyle ISHM05 (including UV blue lens) - Grey",
        mkt:"Reliance Vision Express Pvt Ltd",
        dis:22,
        aprice:342,
        cat:"eyewear",
        rat:3.55,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Kapiva Wheat Grass Juice 1 ltr",
        mkt:"Adret Retail Pvt Ltd, (Kapiva)",
        dis:53,
        aprice:674,
        cat:"ayush",
        rat:4.55,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/958796/nitethru_advanced_sleep_aid_capsule_30s_0_0.jpg",
        name:"Nitethru Advanced Sleep Aid Capsule 30's",
        mkt:"Strides Consumer Pvt Ltd",
        dis:21,
        aprice:211,
        cat:"fitness",
        rat:5.64,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/918432/pro360_mom_nutritional_protein_powder_swiss_chocolate_flavour_400_gm_0_0.jpg",
        name:"Pro360 MOM Nutritional Protein Powder - Swiss Chocolate Flavour 400 gm",
        mkt:"GMN HEALTHCARE PRIVATE LTD",
        dis:43,
        aprice:685,
        cat:"mom",
        rat:3.56,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/947286/fingertip_pulse_oximeter_mi303_0_0.jpg",
        name:"",
        mkt:"",
        dis:23,
        aprice:234,
        cat:"diveces",
        rat:4.34,
    },
    {
        img:"www.netmeds.com/images/product-v1/150x150/821307/kapiva_wheat_grass_juice_1_ltr_0_2.jpg",
        name:"Fingertip Pulse Oximeter (MI303)",
        mkt:"Mkt: Meet Imports",
        dis:43,
        aprice:574,
        cat:"surgicals",
        rat:3.4,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/985297/univen_powder_free_nitrile_gloves_m_100s_0_1.jpg",
        name:"UniVen Powder Free Nitrile Gloves (M) 100's",
        mkt:"Mkt: Univen Healthcare Pvt Ltd",
        dis:23,
        aprice:324,
        cat:"sexual",
        rat:4.2,
    },
    {
        img:"https://www.netmeds.com/images/product-v1/150x150/100424/2baconil_tts10_7mg_patch_7_s_0.jpg",
        name:"2baconil TTS10 7mg Patch 7'S",
        mkt:"Rusan Health Care Pvt Ltd",
        dis:43,
        aprice:464,
        cat:"treatments",
        rat:4.3,
    },
]
localStorage.setItem("productDetaBase",JSON.stringify(productDetabase))